name: Proof Nightly

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

concurrency:
  group: proof-nightly
  cancel-in-progress: true

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r spec_pack/requirements.txt || pip install --quiet pyyaml z3-solver

      - name: A2H semantics
        run: python3 spec_pack/tools/a2h_semantics.py --check

      - name: Compile A2H (emit)
        run: python3 spec_pack/tools/a2h_compile.py --emit

      - name: Emit A2H semantics proof
        run: python3 spec_pack/tools/a2h_semantics.py --emit

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: proof-nightly-${{ github.run_id }}
          path: |
            spec_pack/compiled/**
            spec_pack/metrics.json
            spec_pack/trace.graph.json
            spec_pack/samples/journal.ndjson
